#!/usr/bin/env bash
# RS-vs-HS performance benchmark → README-ready markdown tables.
#
# Runs each representative theory file through BOTH provers at several core
# counts, measuring wall-clock and peak resident memory.  Emits one markdown
# table per core count to stdout.  Regenerate the README figures with:
#
#   rust/scripts/bench.sh > /tmp/bench.md
#
# Env knobs:
#   FILES    space-separated relpaths under examples/ (default: representative set)
#   CORES    space-separated core counts            (default: "1 4 16")
#   TIMEOUT  per-run wall-clock cap, seconds        (default: 600)
#   DERIV    --derivcheck-timeout passed to both    (default: 30)
#   HS_PATH / RS_PATH   override the binaries
#
# Methodology:
#   - Core control: HS `+RTS -Nk -RTS`; RS `--processors=k` (its Maude pool
#     auto-sizes to max(1, k/2)).  Both prove all lemmas (`--prove`).
#   - "peak RSS" is the prover PROCESS only (/usr/bin/time -v "Maximum resident
#     set size").  Maude runs as separate subprocess(es) on BOTH sides and is
#     not counted — the comparison is GHC-heap vs Rust-heap.
#   - Single run per cell (wall-clock is noisy by ±10%; magnitudes are stable).
set -uo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
CORPUS="$repo_root/examples"
TIMEOUT="${TIMEOUT:-600}"
DERIV="${DERIV:-30}"
CORES="${CORES:-1 4 16}"
FILES="${FILES:-classic/NSPK3.spthy wireguard/wireguard.spthy ake/bilinear/Joux.spthy features/auto-sources/tamarin-repo/sapic/statVerifLeftRight/stateverif_left_right.spthy features/auto-sources/spore/CCITT_X509_3.spthy}"

find_hs() { ls "$repo_root"/.stack-work/install/*/*/*/bin/tamarin-prover 2>/dev/null | head -1; }
HS_PATH="${HS_PATH:-$(find_hs)}"
RS_PATH="${RS_PATH:-$repo_root/rust/target/release/tamarin-prover}"
[ -x "$HS_PATH" ] || { echo "bench.sh: no HS binary (set HS_PATH)" >&2; exit 2; }
[ -x "$RS_PATH" ] || { echo "bench.sh: no RS binary at $RS_PATH" >&2; exit 2; }
command -v /usr/bin/time >/dev/null || { echo "bench.sh: needs GNU /usr/bin/time" >&2; exit 2; }

# measure <cmd...> → prints "<secs>|<mb>" (or "timeout|—" on cap).
measure() {
    local e rc wall rss
    e=$(mktemp)
    timeout "$TIMEOUT" /usr/bin/time -v "$@" >/dev/null 2>"$e"; rc=$?
    if [ "$rc" = 124 ]; then rm -f "$e"; printf 'timeout|—'; return; fi
    wall=$(awk -F': ' '/Elapsed \(wall clock\)/{print $NF}' "$e")
    rss=$(awk -F': ' '/Maximum resident set size/{print $NF}' "$e")
    rm -f "$e"
    awk -v w="$wall" -v k="$rss" 'BEGIN{
        n=split(w,a,":");
        s=(n==3)? a[1]*3600+a[2]*60+a[3] : (n==2)? a[1]*60+a[2] : w;
        printf "%.1f|%.0f", s, k/1024 }'
}

cell_t() { [ "$1" = timeout ] && printf 'timeout' || printf '%s s' "$1"; }
cell_m() { [ "$1" = "—" ] && printf '—' || printf '%s MB' "$1"; }

echo "<!-- generated by rust/scripts/bench.sh ($(uname -m) Linux, $(nproc) cores) -->"
for k in $CORES; do
    echo
    echo "**${k} core$([ "$k" = 1 ] && echo '' || echo 's')** — HS \`+RTS -N${k}\`, RS \`--processors=${k}\`"
    echo
    echo "| File | HS wall | RS wall | HS peak RSS | RS peak RSS |"
    echo "|------|--------:|--------:|------------:|------------:|"
    for f in $FILES; do
        af="$CORPUS/$f"
        [ -f "$af" ] || { echo "| \`$f\` | (missing) | | | |"; continue; }
        h=$(measure "$HS_PATH" +RTS -N${k} -RTS --derivcheck-timeout="$DERIV" --prove "$af")
        r=$(measure "$RS_PATH" --processors="$k" --derivcheck-timeout="$DERIV" --prove "$af")
        echo "| \`${f##*/}\` | $(cell_t "${h%|*}") | $(cell_t "${r%|*}") | $(cell_m "${h#*|}") | $(cell_m "${r#*|}") |"
    done
done
echo
echo "BENCH_DONE"
